name = "telegram-bot"
main = "worker.js"
compatibility_date = "2023-05-18"

account_id = "dcb5cb4caca718bf2af93c10267ac007"  # Ganti dengan account ID Cloudflare Anda
workers_dev = true

[vars]
TELEGRAM_TOKEN = "7644792138:AAGRKJmmuFz8axrc85Xm4lXy9BbJ4GNxzzw"  # Ganti dengan token bot Telegram Anda

