name = "telegram-bot"
main = "worker.js"
compatibility_date = "2023-05-18"

account_id = "dc6c48cef8178de1a131e82097bf55bb"  # Ganti dengan account ID Cloudflare Anda
workers_dev = true

[vars]
TELEGRAM_TOKEN = "7644792138:AAGRKJmmuFz8axrc85Xm4lXy9BbJ4GNxzzw"  # Ganti dengan token bot Telegram Anda

