name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Menggunakan Node.js versi 20.x

      - name: Install dependencies
        run: |
          npm install

      - name: Run wrangler config
        run: |
          wrangler config --api-token ${{ secrets.CF_API_TOKEN }}

      - name: Deploy to Cloudflare Workers
        run: |
          wrangler publish
